### ISSUE TITLE
Check for missing fields in Program Impacts

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO-CIAT#123]
Missing fiels are not being displayed

!
[image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-c5b07063001046f2a7f9c8a49656bef24ce28c3ba03cccde950c95107b27f5b9.png)

**Comment by HermesJim** [comment]
Fixed!

![image](https://cloud.githubusercontent.com/assets/13221179/21185029/0d9cff56-c1dd-11e6-8f83-ae955af90358.png)
