### ISSUE TITLE
Allow Impact Pathway navigation header when the pusher blocks the user.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO-CIAT#129]
![image](https://cloud.githubusercontent.com/assets/13221179/21908219/d65e1b72-d8e0-11e6-9525-c7eaddf50a88.png)

**Comment by sebas932** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-fc40d1b4be76b1b11d6d168b9e8d502d5ee3365d896f28bb8a1a693d1e9bd72d.png)
