### ISSUE TITLE
Delete concurrence Block in Outcomes and Output List.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO-CIAT#144]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-1285d565dc6b13e76ec2fb790f521be822a297700dc14ebd46f2c38aae495f69.png)

**Comment by sebas932** [comment]
Fixed 
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-a0cee633b7bb39afc8fa9cee2bccc9a889d828c0288de8266e35b7569730ad18.png)
