### ISSUE TITLE
Create outcomes interface - monitoring

### ISSUE THREAD

**Issue by carios1usb** [CCAFS/MARLO-CIAT#169]

**Comment by HermesJim** [comment]
@carios1usb  has implemented the outcomes interface.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-76719a4bbdb8902a300c2d3de02365a7dd7e25567fe515fb3affa7fe881839b0.png)

**Comment by HermesJim** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9b998b34e51e81d7ab10e47477e987f018b2242a7fb46e698bb98f5d8328b82b.png)
