### ISSUE TITLE
Setup Local Environment for CIAT-MARLO

### ISSUE THREAD

**Issue by nmatovu** [CCAFS/MARLO-CIAT#17]
Install the required technologies and frameworks (Git, Java, MySQL, Eclipse, etc)
Setup database baseline
Setup Github repository within CCAFS
Run project for the first time (Hello World)
Develop login page

**Comment by htobon** [comment]
Hi Noah, I think this card is a major issue. As you have splitted it in several issues. Let's close it and keep the track with the others.
