### ISSUE TITLE
Installation guide in English and updated with latest versions

### ISSUE THREAD

**Issue by nmatovu** [CCAFS/MARLO-CIAT#18]
Writing an installation guide for MARLO-CIAT in English and updated with latest versions

**Comment by htobon** [comment]
Hi Noah, which is the file where you are working?
There are 3 files in there.
Cheers,

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f082d8de8cf70c75d475dd75f0f147caec4415fcb2801886ceda1a027fa712ba.png)

**Comment by nmatovu** [comment]
https://docs.google.com/document/d/11SINpxT7tzXDdCfNQfq7S5XfHw_C8TLp_nSf2tdIJ9s/edit?usp=sharing

**Comment by htobon** [comment]
Thank you @nmatovu, let's close this issue as the document seems to be done.
