### ISSUE TITLE
Delete Double Submit Confirmation PopUp

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO-CIAT#181]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-5fd102e1a680829e139c22370878f9f76a84b153ee431688f065b56bae34a69d.png)

**Comment by carios1usb** [comment]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-ee4469a8dc9572d984a240cfb770f1aa3080966cd035a1267fa0cff58931a276.png)
