### ISSUE TITLE
Merge MARLO CIAT DB with MARLO DB

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO-CIAT#206]

**Comment by HermesJim** [comment]
Merge complete.
The table and files changes are document in : https://docs.google.com/spreadsheets/d/135ZGTJGMKnBkn1A1BpGZ3DB6Bj3jUbQLY6A1YtOgV2k/edit#gid=1185679553

**Comment by htobon** [comment]
Good job!
