### ISSUE TITLE
Develop login page

### ISSUE THREAD

**Issue by nmatovu** [CCAFS/MARLO-CIAT#26]

**Comment by sebas932** [comment]
Hi Noah, i tried to install MARLO CIAT from the repository, but i got an error executing `mvn clean install`, im not sure if there is something missing in the repository.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-2e43aaaee9fb43c2cfe8368ac07d514c9f154f55f02624c43529fecb1aff7006.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-9aa8795df5c770a0e911b2aae969956ee9372ffdb5854afce5f6e30abb1e1fd3.png)
