### ISSUE TITLE
Create Research Topics/Flagship Projects

### ISSUE THREAD

**Issue by nmatovu** [CCAFS/MARLO-CIAT#28]
Create Research Topics/Flagship Projects

**Comment by htobon** [comment]
Almost finished but still need work.

**Comment by HermesJim** [comment]
@htobon i make interface and technical changes in this section, please check if this section is finished.

**Comment by htobon** [comment]
Hi @HermesJim, the history is not working properly, kindly review it and make the corresponding fixes.

**Comment by htobon** [comment]
This issue will be followed in the issue #76
