### ISSUE TITLE
Create Database Tables for Research Area

### ISSUE THREAD

**Issue by nmatovu** [CCAFS/MARLO-CIAT#31]
Create Database Tables for Research Area (research programs, research area, research leader).

**Comment by htobon** [comment]
@HermesJim, may you please attach the database model just to quickly confirm everything is ok?

**Comment by HermesJim** [comment]
The tables has been created, in the issue #39 i created a spreadsheet whit the information of the research areas and research programs.

https://docs.google.com/spreadsheets/d/1CmcPwg9Dap01Rg2FVFeaLgp6C2dC15HiiV7QeIRLqZM/edit#gid=0

**Comment by HermesJim** [comment]
@htobon  now there is implemented the database model from impactpathway.

![image](https://cloud.githubusercontent.com/assets/13221179/19647864/aee205ea-99c5-11e6-87a5-3909a912443f.png)

**Comment by htobon** [comment]
Thank you @HermesJim. Please apply the suggested changes according to our discussion in my office.

**Comment by HermesJim** [comment]
![image](https://cloud.githubusercontent.com/assets/13221179/19649439/6a13b07a-99cb-11e6-8578-ce4a5a95db0c.png)

i have done the changes in the model database.
