### ISSUE TITLE
Create Program Impacts Interface

### ISSUE THREAD

**Issue by nmatovu** [CCAFS/MARLO-CIAT#33]
Create Program Impacts Interface

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-7e1d6981d6224dc8838b704bff56abb4b813ed2d06fb788c29aa65a616950853.png)

**Comment by htobon** [comment]
Not finished yet.

**Comment by HermesJim** [comment]
To complete the Program Interface .. we need to define the beneficiaries list .
issue #46

**Comment by HermesJim** [comment]
move to the next milestone.

**Comment by HermesJim** [comment]
Add the beneficiaries list interface..

![image](https://cloud.githubusercontent.com/assets/13221179/20715541/8894a6e4-b61d-11e6-90df-71c0e62c20b3.png)

With this implementation, program impact interface is finalized.
