### ISSUE TITLE
Define the Beneficiaries List in Research Impacts. 

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO-CIAT#46]
Define the information that will have the Beneficiaries List in Research Impact.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-90ecc32f04a4d68c31039f1af80a8f4749a561e6c6a3c5c69ddcd36839404ddf.png)

https://docs.google.com/presentation/d/1xSxp1sowho2vDm_2mjlgmmqAPPhNR3OD_eqFFUWKHR4/edit#slide=id.g13483776f3_0_117

**Comment by nmatovu** [comment]
@HermesJim please I have some questions on this issue, will contact you on Slack.

**Comment by htobon** [comment]
Hi @nmatovu, don't worry about it. Indeed it is not clear for us too. Please let this issue here in review until I ask the M&E Experts (Perla and Sohpie) here at CIAT how to proceed.

**Comment by HermesJim** [comment]
the update list of beneficiaries list are in https://docs.google.com/spreadsheets/d/1oKQ1QtbQCrTZ-qwWcPtbI5QQVGQzfeRB7vxaunPWgD4/edit#gid=130631238
