### ISSUE TITLE
Create List of Intended Beneficiaries Section

### ISSUE THREAD

**Issue by nmatovu** [CCAFS/MARLO-CIAT#50]
Create List of Intended Beneficiaries Interface Section

**Comment by htobon** [comment]
Hi @nmatovu, this list needs to be created by the CIAT M&E Team. I'll ask them today what to do ok? I will keep you and @HermesJim informed here.

**Comment by HermesJim** [comment]
Closed.
The beneficiaries list is in the issue #46
