### ISSUE TITLE
Implement missing fields Functionality 

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO-CIAT#56]

**Comment by HermesJim** [comment]
I Implement the missing filed functionality in the two actives sections.

@htobon  please check if these functionality works. 

![image](https://cloud.githubusercontent.com/assets/13221179/19948014/9e047cf8-a118-11e6-8649-54e9fd182279.png)

**Comment by htobon** [comment]
Closing this issue and the missing fields will be followed-up on separated issues.
