### ISSUE TITLE
implement decision tree in the dashboard

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO-CIAT#57]

**Comment by HermesJim** [comment]
I implement the decision tree, for now only work the first link (Define your Impact).

please @htobon  check in Marlo CIAT dev these implementation.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f7b54ca01d93a9ff6ead6149a78996d4398b00b7d11103c5f54cfcc3305ddef8.png)

**Comment by htobon** [comment]
Great. thks
