### ISSUE TITLE
Outcomes List Interface

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO-CIAT#58]

**Comment by htobon** [comment]
Hi @HermesJim, please add an aclaratory message when an specific Research Topic does not have outcomes added as of yet. Please refer to the screesnhot below:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-d03bda90f4dcdeaeef89a4ebb5f160cec1ea43190ee2489e3d337a431479d025.png)

**Comment by HermesJim** [comment]
I add the text box when the research topic has not outcomes.

![image](https://cloud.githubusercontent.com/assets/13221179/20324399/7273c022-ab4e-11e6-8590-0670a3c1e345.png)

**Comment by HermesJim** [comment]
@htobon plase check if the issue is done please.

this changes is now in marlo ciat dev.

**Comment by htobon** [comment]
remove white spaces between the quotes
