### ISSUE TITLE
Create Outcomes Interface

### ISSUE THREAD

**Issue by sebas932** [CCAFS/MARLO-CIAT#68]

**Comment by HermesJim** [comment]
![image](https://cloud.githubusercontent.com/assets/13221179/20230454/0ef2cfec-a82a-11e6-8235-8140904593be.png)

**Comment by HermesJim** [comment]
![image](https://cloud.githubusercontent.com/assets/13221179/20230461/1a1e53be-a82a-11e6-81a3-229882afd86e.png)

**Comment by HermesJim** [comment]
the implementation of outcomes section.
