### ISSUE TITLE
Saving in the outcome section

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO-CIAT#70]
I went inside an outcome, and then clicked the save button. I got a message saying that the inforamtion was not saved and some fields were reseted.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-0b37aa6c5b5437276f0ba5b608d57542f0027bafb0250f76236cef26224a2392.png)

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-4f32e4152889d526bb41557ba358cf024f8d7823709d852d7f5363d69796ecaf.png)

**Comment by HermesJim** [comment]
I fix the issue, the outcomes section save the information.

![image](https://cloud.githubusercontent.com/assets/13221179/20324351/41baf81a-ab4e-11e6-8aea-18b3e3b07e1d.png)

**Comment by HermesJim** [comment]
@htobon  plase check if the issue is done please.

this changes is now in marlo ciat dev.

**Comment by htobon** [comment]
The target value for the milestones is not saving.

**Comment by HermesJim** [comment]
Fix the issue on the target value in milestones

![image](https://cloud.githubusercontent.com/assets/13221179/20352511/80eefa12-abe5-11e6-8668-9e9ff7736984.png)
