### ISSUE TITLE
Delete icon in the outcomes list section

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO-CIAT#71]
Hi @HermesJim, may you please add a delete button in the outcomes list section?

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-696db2ec4b988aabc71566a0e53a09c078ac1cc98042c2e5220a74134f458244.png)

**Comment by HermesJim** [comment]
the delete outcomes has been added in the outcomes list.

![image](https://cloud.githubusercontent.com/assets/13221179/20324474/bf2f3c7a-ab4e-11e6-937e-036a5c299095.png)

**Comment by HermesJim** [comment]
@htobon plase check if the issue is done please.

**Comment by htobon** [comment]
Please include a popup for confirming the deletion.

> "Are you sure you want to remove this outcome?
> YES / NO"

**Comment by HermesJim** [comment]
I added a popup whit a text justification.

![image](https://cloud.githubusercontent.com/assets/13221179/20352721/514e0252-abe6-11e6-8ff6-ffc261615372.png)
