### ISSUE TITLE
Tracking history not working properly in Program Impacts

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO-CIAT#72]

**Comment by HermesJim** [comment]
The track changes and the editable mode works in program impact section.

![image](https://cloud.githubusercontent.com/assets/13221179/20324534/fa099a16-ab4e-11e6-9edb-f4f12a9c1066.png)

![image](https://cloud.githubusercontent.com/assets/13221179/20324541/ffc89f92-ab4e-11e6-90f3-2cdec9468a4d.png)

**Comment by htobon** [comment]
thks. The history is working but the message in grey that displays the date of the history when you click in some previous is not loading.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-f3be0580b40da80225f9e913f9e79a91f6ca580e6e392b66cdf3666b4ff01a50.png)

**Comment by HermesJim** [comment]
I fixed the history text.

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-11a1e35a4abb793d4b8427604d749dc0cb485adfc0a311bbd8b50f92f5ecd8fa.png)
