### ISSUE TITLE
Missing field in Program Impacts is not being displayed properly

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO-CIAT#73]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-0c052b10e88c9ff715df32ae8cd3636e98b8fdb5f59ad8b25cf9ad8bf2555ae2.png)

**Comment by HermesJim** [comment]
I border in red the combo box..

![image](https://cloud.githubusercontent.com/assets/13221179/20324818/10c2b3ea-ab50-11e6-85e0-a076cd9cb685.png)
