### ISSUE TITLE
Disable delete button in Research Topics section

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO-CIAT#74]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-7bd61ead899a53cfddef9d6cd492d1f371e1121c604d62b6473b49378de306c3.png)

**Comment by HermesJim** [comment]
I Implemented this functionality in Research topics and research impact section.

![image](https://cloud.githubusercontent.com/assets/13221179/20324867/3d84e2ea-ab50-11e6-96c5-9e954200c9b0.png)
