### ISSUE TITLE
History of Changes in Research topics is not working properly

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO-CIAT#76]
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b934caf5beedb985563825951c0741c6ef9db64f4e44cdd4a09a7fc44317207a.png)

**Comment by HermesJim** [comment]
The track changes and editable mode works in research topics section.

![image](https://cloud.githubusercontent.com/assets/13221179/20324678/6190800a-ab4f-11e6-844b-b81f9221c1b0.png)

![image](https://cloud.githubusercontent.com/assets/13221179/20324682/68986142-ab4f-11e6-98cb-fbc1590e83e0.png)

**Comment by HermesJim** [comment]
@htobon plase check if the issue is done please.
