### ISSUE TITLE
Research Topic in read mode in Outcomes section

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO-CIAT#77]
Please make read only the list of research topics if the user is inside a specific Outcome. Pelase refer to the screesnhot below:

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-886b1e66c702dfd2e6337be5bfc50b447af04615fce2f85bad6619f64ba0d1b4.png)

**Comment by HermesJim** [comment]
I delete the research topics list in outcomes section and replace it by a no editable text label.

![image](https://cloud.githubusercontent.com/assets/13221179/20324645/43318a6e-ab4f-11e6-808f-c167c4ef5da0.png)

**Comment by HermesJim** [comment]
@htobon plase check if the issue is done please.
