### ISSUE TITLE
Typo fix in Milestones

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO-CIAT#78]
Text should be: "There are not Milestones associated to this Research Topic as of yet."

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-7ca0221e48fb7bbbfc0703d93dd45cc5c5f3769baa29791ce685c82f1cd9647c.png)

**Comment by HermesJim** [comment]
the text has been change..

![image](https://cloud.githubusercontent.com/assets/13221179/20324501/d64c3e6c-ab4e-11e6-8f27-8e2cc6972903.png)
