### ISSUE TITLE
Put CIAT logo.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO-CIAT#94]

**Comment by HermesJim** [comment]
![image](https://cloud.githubusercontent.com/assets/13221179/20538627/06f795e0-b0c0-11e6-8fed-4bdda85c43ca.png)


the CIAT logo appears when the user is logged in .

**Comment by htobon** [comment]
Please also include the logo when the user is not logged in.

**Comment by HermesJim** [comment]
Change implemented..

![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-b77dcddbbe06086c1ea63014ad62d0c1c148d52ffda52098587ce3bb7ff37a08.png)
