### ISSUE TITLE
Outputs Sub menu interface.

### ISSUE THREAD

**Issue by HermesJim** [CCAFS/MARLO-CIAT#95]

**Comment by nmatovu** [comment]
@HermesJim Is this task related to this as seen in the screenshot? ![output sub menu.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/output%20sub%20menu-279ba01632387bc8c4d0ceef0dd407cc1ac5bf96eedd9f54fd6af35a7308c6aa.png)

**Comment by HermesJim** [comment]
with the help of @sebas932 ... implement the new output menu navigation.

![image](https://cloud.githubusercontent.com/assets/13221179/20674960/b8421216-b558-11e6-80ed-61dfb1056e73.png)
