### ISSUE TITLE
Update mockup (Outputs section)

### ISSUE THREAD

**Issue by htobon** [CCAFS/MARLO-CIAT#98]
Please merge the "Next-users" section into the "Main Information" section.

The idea would be to only have two sub-sections in Outputs:

1. Main information
2. Partners

Please apply the changes in our shared mockup.

**Comment by HermesJim** [comment]
With the help of @sebas932 . we change the outcomes navigation, and merge the next-users section on output main information. 
to see this proposal , I update the mockups (Slide 16-17-18)  with the interface changes.

https://docs.google.com/presentation/d/1xSxp1sowho2vDm_2mjlgmmqAPPhNR3OD_eqFFUWKHR4/edit#slide=id.g13483776f3_2_179
